### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by EsimioJ** [robmcrosby/BlenderUSDZ#24]
i'm tryng to install the plugin in the normal way
this is the console:
Modules Installed () from '/Users/apo/Downloads/BlenderUSDZ-master.zip' into '/Users/apo/Library/Application Support/Blender/2.80/scripts/addons'

every thing seems to work but then I can't find the plugin in the installed list

**Comment by robmcrosby** [comment]
My guess is that you downloaded the repo as a zip file. You will need to
unzip BlenderUSDZ-master.zip and then install using io_scene_usdz.zip
