### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by hexagons** [robmcrosby/BlenderUSDZ#34]
Also reported [here](https://developer.blender.org/T72998) on the Blender forum.
<img width="700" alt="Skärmavbild 2020-01-09 kl  15 40 27" src="https://user-images.githubusercontent.com/7947442/72077155-0f1b9c00-32f7-11ea-9de9-c628525b2b7e.png">

**Comment by robmcrosby** [comment]
This plugin was not intended to work with older versions of blender bellow version 2.80.

**Comment by hexagons** [comment]
Ok, I will upgrade, thanks!
