### ISSUE TITLE
Import of *.usdz from iOS app "Capture" doesnt work

### ISSUE THREAD

**Issue by kpek** [robmcrosby/BlenderUSDZ#42]
Hello,

I made test 3D scan of my face using the Capture app on iphone xs (https://apps.apple.com/us/app/capture-3d-scan-anything/id1444183458) which saves the 3D scans as *.usdz files.
I sent it to myself via email from the app and tried to import into Blender using your script, but theres nothing imported in the scene.
In Blender console it says "No usdc file found"

I know usdz is just zip file with other usd* files. so i tried to manually export the *.usdc file from the usdz and tried also to import directly *.usdc file, but nothing is imported, and with *.usdc theres no message in the log at all.

Then as last thing i tried to "zip" the exported usdc file again with zero compression (and putting the usdc file at the root of the zip), and renamed it to *.usdz. That actually imported something into Blender, i see vertex and face counts, but nothing really visible on screen and the location of the imported model was waay out somewhere - see first screenshot.
I moved the whole object to 0 0 0 and now i see single vertex like object in the middle of the screen which i tried to resize, but doenst help, it stays like that. 

![import1](https://user-images.githubusercontent.com/3976797/75907771-2f745c80-5e49-11ea-9151-f427de60a839.png)
![import2](https://user-images.githubusercontent.com/3976797/75907777-31d6b680-5e49-11ea-987d-bb1c863501f9.png)

Capture is one of the fully free 3D scan apps afaik (for now and hopefully forever) supporting the TrueDepth camera on newer iphones so it would be really cool if this was fixed :)

BR,
Adam

**Comment by kpek** [comment]
BTW iam using windows 10 (i saw in readme it might not work) and Blender 2.82

**Comment by robmcrosby** [comment]
Thanks for the feed back. I wonder if the 3D scan app is exporting the usd file as the text version. When you expanded the usdz file was there a usda file? If that is the case I still need to write a parser for the text version of usd. The usdc file might have been setup in a way the plugin was not able to read. If you need an immediate workaround you could try opening and exporting the usdz file with the beta Reality Converter app if you have access to a mac and a developer account.

**Comment by kpek** [comment]
Hi,

No there was not *.usda file inside.

Heres the full "Capture" app *.usdz file structure:

C:\Users\XXXX\Downloads\Scan>tree /F
Folder PATH listing for volume XXXXX
Volume serial number is XXXXXXX XXXX:XXXX
C:.
└───private
    └───var
        └───mobile
            └───Containers
                └───Data
                    └───Application
                        └───FDB0B90B-A937-4E22-8572-C40AD5F7EEF3
                            └───tmp
                                    Scan.usdc

I dont need immediate workaround (started playing with this  whole 3d capture thing only yesterday), just pointing out the functionality issue. Yes, I have a mac and also developer account, will try what you suggested tonight. 

BR,
Adam

**Comment by robmcrosby** [comment]
Got some fixes in that allows import of usdz files from the Capture app.
