### ISSUE TITLE
Model doesn't show on iPhone

### ISSUE THREAD

**Issue by DeCodeR-97** [robmcrosby/BlenderUSDZ#44]
Hi, when I export a model to usdz, it does not show in AR Quick Look on my iPhone (not in AR View, nor in Object View).  However, it shows perfectly in Quick Look on my Mac.
Does anyone have an idea where the problem could be?
I'm using Blender 2.82a and iOS 13.3.1 on my iPhone X

**Comment by robmcrosby** [comment]
Not sure exactly what is going on here. One way where a model will show on the Mac but not on iOS would be if the model was exported as a usda file which the plugin can export if you name your file with the .usda extension. If this is the case, be sure to either leave off the extension on the file name or explicitly add the .usdz extension when exporting.

**Comment by DeCodeR-97** [comment]
Thanks for the reply.. the file has the .usdz extension and i can open it on my iphone. It opens up AR QuickLook but doesn‘t show anything.

**Comment by JUGAL3D** [comment]
If you can share your file here, I could come up with a solution for you.

**Comment by JUGAL3D** [comment]
Possible issues could be that your scene scale is too large.

**Comment by DeCodeR-97** [comment]
Unfortunately I can't share my file. When I tried to make a few similar models to share with you and show you the issue, I noticed that the files work fine (also on iOS). Could it be that I get the issue because I created the original blender file in blender 2.7?

**Comment by JUGAL3D** [comment]
nothing as such. You could try these things.
Make sure the mesh namings are short and proper.
UV set naming are short and proper
Try this by exporting a single mesh in the scene to see if it works

**Comment by DeCodeR-97** [comment]
Both my mesh naming and UV set namings are short and should also be proper since I tried using the same for other models where AR QuickLook worked. Seems to be a strange issue, however, I'm closing this now because I'm getting the error for one blender file only. Maybe I just messed up some preferences. Thanks for your help.
