### ISSUE TITLE
Add-on won't install.

### ISSUE THREAD

**Issue by Archi97** [robmcrosby/BlenderUSDZ#51]
Hi,  when im installing add-on by choosing zip file, blender seems to be installing.  but i cant find it in my add-on list.  i have looked everywhere. It is just not exist.

**Comment by applebait** [comment]
You must unzip it first, inside the "firt" zip file there's the io_export_usdz.zip.

**Comment by ostapvovk3pc** [comment]
I unzipped it and its still not showing up on the blender page.

**Comment by j04ntoh** [comment]
upgrade your blender

**Comment by Liferocka** [comment]
Hi, I have the latest version of blender 3.0 and its not installing for me either? Well, I unzipped it ll. installed it but it won't show up in the add ons list.
